version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_simple_container
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_simple_container
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1"  # create topic 'my-topic' with 1 partition and 1 replica

